import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import test from 'node:test';
import { loadContract, toRestFunctionName } from '../helpers/contract.mjs';
import { getEnv, getTimeout, requireEnv, resolveCliCommand } from '../helpers/env.mjs';
import { callMcp } from '../helpers/mcp.mjs';
import { callRestFunction } from '../helpers/moodle-rest.mjs';
import { fromRoot } from '../helpers/paths.mjs';

const execFileAsync = promisify(execFile);
const hasTransportConfig = requireEnv(['MOODLE_BASE_URL', 'MOODLE_REST_TOKEN']);

async function callMcpTool(name, toolArguments = {}) {
  return callMcp('tools/call', {
    name,
    arguments: toolArguments
  });
}

async function callCli(args) {
  const configured = resolveCliCommand();
  const localCli = fromRoot('cli/moodle-mcp.mjs');
  const commandPath = configured ?? localCli;
  const command = commandPath.endsWith('.mjs') || commandPath.endsWith('.js') ? process.execPath : commandPath;
  const commandArgs = command === process.execPath ? [commandPath, ...args, '--format', 'json'] : [...args, '--format', 'json'];
  const { stdout } = await execFileAsync(command, commandArgs, {
    timeout: getTimeout(),
    env: {
      ...process.env,
      MOODLE_BASE_URL: getEnv('MOODLE_BASE_URL'),
      MOODLE_REST_TOKEN: getEnv('MOODLE_REST_TOKEN')
    }
  });

  return JSON.parse(stdout.trim());
}

function normalizeCourseCompletion(payload) {
  return {
    course_id: Number(payload.course_id),
    user_id: Number(payload.user_id),
    completed: Boolean(payload.completed),
    aggregation: Number(payload.aggregation),
    criteria_count: Number(payload.criteria_count),
    completed_criteria_count: Number(payload.completed_criteria_count),
    has_status_json: typeof payload.status_json === 'string',
    warning_count: Array.isArray(payload.warnings) ? payload.warnings.length : -1
  };
}

function normalizeActivityCompletion(payload) {
  assert.ok(Array.isArray(payload.statuses), 'statuses must be an array');
  assert.ok(Array.isArray(payload.warnings), 'warnings must be an array');

  return {
    course_id: Number(payload.course_id),
    user_id: Number(payload.user_id),
    status_count: payload.statuses.length,
    warning_count: payload.warnings.length
  };
}

function normalizeProgressReport(payload) {
  assert.ok(Array.isArray(payload.users), 'users must be an array');
  assert.ok(Array.isArray(payload.warnings), 'warnings must be an array');

  return {
    course_id: Number(payload.course_id),
    requested_limit: Number(payload.requested_limit),
    returned_user_count: Number(payload.returned_user_count),
    total_enrolled_user_count: Number(payload.total_enrolled_user_count),
    grade_item_count: Number(payload.grade_item_count),
    tracked_activity_count: Number(payload.tracked_activity_count),
    completed_user_count: Number(payload.completed_user_count),
    average_grade_percentage: Number(payload.average_grade_percentage),
    user_count: payload.users.length,
    warning_count: payload.warnings.length,
    first_user_keys: payload.users[0] ? Object.keys(payload.users[0]).sort() : []
  };
}

test('REST, MCP, and CLI expose course and activity completion status reads', {
  skip: !hasTransportConfig
}, async () => {
  const contract = await loadContract();
  const suffix = `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const currentUser = await callRestFunction(toRestFunctionName(contract, 'get_current_user'), {});
  const category = await callRestFunction(toRestFunctionName(contract, 'create_course_category'), {
    name: `MoodlIA Completion Smoke ${suffix}`,
    visible: true
  });
  const course = await callRestFunction(toRestFunctionName(contract, 'create_course'), {
    fullname: `MoodlIA Completion Smoke Course ${suffix}`,
    shortname: `moodlia-completion-${suffix}`,
    category_id: category.category_id,
    visible: true,
    summary: '<p>Generated by MoodlIA completion smoke tests.</p>',
    summary_format: 'html'
  });
  const courseId = Number(course.course_id);

  try {
    await callRestFunction(toRestFunctionName(contract, 'enrol_user'), {
      course_id: courseId,
      user_id: currentUser.id,
      role_archetype: 'student'
    });

    const restCourse = normalizeCourseCompletion(await callRestFunction(
      toRestFunctionName(contract, 'get_course_completion_status'),
      { course_id: courseId }
    ));
    const mcpCourse = normalizeCourseCompletion(await callMcpTool('get_course_completion_status', {
      course_id: courseId
    }));
    const cliCourse = normalizeCourseCompletion(await callCli([
      'get-course-completion-status',
      '--course-id', String(courseId)
    ]));

    assert.deepEqual(mcpCourse, restCourse, 'MCP course completion shape must match REST');
    assert.deepEqual(cliCourse, restCourse, 'CLI course completion shape must match REST');

    const restActivities = normalizeActivityCompletion(await callRestFunction(
      toRestFunctionName(contract, 'get_activity_completion_statuses'),
      { course_id: courseId }
    ));
    const mcpActivities = normalizeActivityCompletion(await callMcpTool('get_activity_completion_statuses', {
      course_id: courseId
    }));
    const cliActivities = normalizeActivityCompletion(await callCli([
      'get-activity-completion-statuses',
      '--course-id', String(courseId)
    ]));

    assert.deepEqual(mcpActivities, restActivities, 'MCP activity completion shape must match REST');
    assert.deepEqual(cliActivities, restActivities, 'CLI activity completion shape must match REST');

    const restProgress = normalizeProgressReport(await callRestFunction(
      toRestFunctionName(contract, 'get_course_progress_report'),
      { course_id: courseId, limit: 5 }
    ));
    const mcpProgress = normalizeProgressReport(await callMcpTool('get_course_progress_report', {
      course_id: courseId,
      limit: 5
    }));
    const cliProgress = normalizeProgressReport(await callCli([
      'get-course-progress-report',
      '--course-id', String(courseId),
      '--limit', '5'
    ]));

    assert.equal(restProgress.requested_limit, 5, 'REST progress report must preserve the requested limit');
    assert.deepEqual(mcpProgress, restProgress, 'MCP progress report shape must match REST');
    assert.deepEqual(cliProgress, restProgress, 'CLI progress report shape must match REST');
  } finally {
    await callRestFunction(toRestFunctionName(contract, 'delete_course'), {
      course_id: courseId
    });
    await callRestFunction(toRestFunctionName(contract, 'delete_course_category'), {
      category_id: category.category_id
    });
  }
});
